### ISSUE TITLE
Can meica.py be made to run with 5d nifti inputs?

### ISSUE THREAD

**Issue by TheChymera** [afniHQ/AFNI#10]
Hi, from the `meica.py` help I notice it takes separate nifti files for each echo time:

```
chymera@zenbookhost ~ $ meica.py -h
Usage: meica.py [options]

Options:
  -h, --help            show this help message and exit
  -e TES                ex: -e 14.5,38.5,62.5  Echo times (in ms)
  -d DSINPUTS           ex: -d RESTe1.nii.gz,RESTe2.nii.gz,RESTe3.nii.gz
```

Is there any way to pass it a 5D file (one with a 5th dimension for the echo times)?

**Comment by nno** [comment]
@TheChymera is this still an issue?

Since the official AFNI is now hosted at https://github.com/afni/afni, we would like to close down afniHQ entirely. If this is still an issue, can you please re-open at https://github.com/afni/afni?

**Comment by nno** [comment]
Thanks @TheChymera for your quick response.
