### ISSUE TITLE
Official AFNI repository

### ISSUE THREAD

**Issue by TheChymera** [afniHQ/AFNI#2]
Hi, which is the official AFNI repository (from where I can prospectively download the latest code for "live" package distributions)?

Is this it? On GitHub, there is at least one other AFNI (organisation)account and a repository containing almost the same directory structure as this one:

https://github.com/afni/rmafni

**Comment by afni-rwcox** [comment]
That was just a test repository when we were messing around with github.  The active one is 

https://github.com/afniHQ/AFNI
