### ISSUE TITLE
Packaging AFNI for Gentoo

### ISSUE THREAD

**Issue by TheChymera** [afniHQ/AFNI#3]
For a while now, I have tried to package AFNI for Gentoo: as seen [in this pull request](https://github.com/gentoo-science/sci/pull/115) with the Gentoo-science repository.

As a short introduction, Gentoo packages (called ebuilds) are not really packages, but rather standardized Makefiles, that can help Portage (the Gentoo "package" manager) compile the software. I have been trying to write such an ebuild for AFNI for a while, but sadly, I am making very slow progress. At present we make the ebuild use your `linux_fedora_19_64` Makefile, which we slightly modify with `sed` and then try to assign run permissions to the files which need them. I might get that to work soon enough, but even so, [here](https://github.com/gentoo-science/sci/pull/115#issuecomment-25465928) is what one of the Gentoo-science maintainers has to say about how AFNI compiles.

Could you perhaps help me address at least some of these points? Or would you even be willing to write a new Makefile for Gentoo, just as you have for fedora?

**Comment by afni-rwcox** [comment]
I read the comments at the link you provided.  And I do not understand why these are issues.

**Comment by afni-rickr** [comment]
The AFNI makefiles are set up explicitly for the machines we compile on.  They are not meant to work on arbitrary systems.  The Gentoo-science maintainer's requests just imply setting up your own Makefile (or possible set of them, to include some sub-directories), and likely altering parts of the build tree.  But note that while we would be happy to add a new Makefile if it makes your life easier, many of the requested changes will have to be done locally in your build environment, not in ours.

The only messy issue in the list might be with strncat, as that affects source code (possibly including automatically generated C files).  But you can save that for later.

The comments about "respecting" variables, not using /bin/rm and not using -fPIC can be dealt with based in this example from the CC definition line:

CC     = /usr/bin/gcc -O2 -m64 -fPIC -DREAD_WRITE_64 -DLINUX2 $(CEXTRA)

1. Respect any existing CC.  That means either assign it only if it does not already exist (using ?=) or try adding to it (using +=).  Actually, you might consider doing both, e.g.
CC ?= gcc ...
CC +=  -DREAD_WRITE_64 -DLINUX2 $(CEXTRA)

2. Do not use full paths.  That is already in example 1, using gcc instead of /usr/bin/gcc.

3. Not using -fPIC.  If they do not want this option in your Makefile, just don't use it.  Example 1 included not using any of  -O2, -m64 or -fPIC, which they do not like.

Anyway, start by going that direction.  Then go after the "bundling and using" issues, which will mean changes to your local build tree, not ours.  Verify with the Gentoo maintainers about the exact techniques (e.g. CC+=) they prefer that you use.

**Comment by TheChymera** [comment]
Many thanks for your answer!

> while we would be happy to add a new Makefile if it makes your life easier

At least the changes which you just described would be (I think) a lot better addressed on your end, by a Makefile which makes a minimum of assumptions? I think it might also be useful as a sort of skeleton  Makefile with which you could start if you want to build it on a new machine/architecture. If we do this on our end it would require quite a bit of `sed`-ing, and would also be prone to breakage if you ever change something in those lines in your makefile.

So, would it be possible for you to just add a `/src/Makefile.linux_gen` (the “gen” can double as gentoo and generic, see how well that fits? ^^) to your repository? Actually, I'll open a pull request myself.

**Comment by yarikoptic** [comment]
you can use cmake build infrastructure which we maintain for building NeuroDebian package of afni.  quick howto

```bash
git clone git@github.com:neurodebian/afni
cd afni
quilt push # will apply debian/patches/cmake_* patches"
```

if you could help maintaining them (atm needs update) that would be awesome

**Comment by TheChymera** [comment]
@yarikoptic 

so I only need the `cmake_*` patches for the cmake build to work? how does quilt know which patches to apply when I run it? Also, would your patches work with patch instead of quilt? (I don't want to depend on quilt for the build process).

**Comment by yarikoptic** [comment]
You can just use patch. Order is specified in series file. I would also need to check if patches are selfsuficient with stock source code which we strip a bit

**Comment by TheChymera** [comment]
@yarikoptic hey again - I am trying to apply the patches with [this bash script snippet](https://github.com/TheChymera/neurogentoo/blob/6f6ba3dad76a4a5ae8ae347b925ee21b3c23211c/sci-biology/afni/afni-9999.ebuild#L44-L48), but the first patch, already seems to fail: [see output here](https://bpaste.net/show/e1b38f78725d). Any ideas what'S up? that's quite a lot of files that can't be found...

**Comment by TheChymera** [comment]
@yarikoptic ?

**Comment by yarikoptic** [comment]
well -- I have no clue in gentoo and its build scripts so it would be for you to figure out what went wrong.  Those patches do contain cmake build system files as you can see:
```bash
$> lsdiff debian/patches/cmake_*
debian/patches/cmake_sharedlibs-cmake:b/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/CMakeLists_apps.txt
debian/patches/cmake_sharedlibs-cmake:b/CMakeLists_libs.txt
debian/patches/cmake_sharedlibs-cmake:b/CMakeLists_plugins.txt
debian/patches/cmake_sharedlibs-cmake:b/R_scripts/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/SUMA/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/avovk/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/coxplot/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/faces/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/poems/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/python_scripts/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/rickr/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/html/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/ptaylor/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/pkundu/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/pkundu/meica.libs/CMakeLists.txt
debian/patches/cmake_sharedlibs-cmake:b/3DEdge/src/CMakeLists.txt
debian/patches/cmake_sharedlibs-noncmake:a/SUMA/SUMA_gts.h
debian/patches/cmake_sharedlibs-noncmake:a/SUMA/SUMA_gts_insert.c
debian/patches/cmake_sharedlibs-noncmake:a/cs_qmed.c
debian/patches/cmake_sharedlibs-noncmake:a/gifti_choice.c
debian/patches/cmake_sharedlibs-noncmake:a/mri_dicom_hdr.c
debian/patches/cmake_sharedlibs-noncmake:a/mri_nstats.c
debian/patches/cmake_sharedlibs-noncmake:a/rickr/Dimon.c
debian/patches/cmake_sharedlibs-noncmake:a/rickr/dimon_afni.c
debian/patches/cmake_sharedlibs-noncmake:a/suma_gifti.c
debian/patches/cmake_sharedlibs-noncmake:a/R_scripts/AFNIio.R
debian/patches/cmake_tests:a/CMakeLists.txt
debian/patches/cmake_tests:b/tests/CMakeLists.txt
debian/patches/cmake_tests:b/tests/xvfb-driver
debian/patches/cmake_tests:a/3DEdge/src/CMakeLists.txt
```
I guess you just need to do it, wait to fail, retrospect what has happened -- where those files were generated (if were at all) etc

**Comment by yarikoptic** [comment]
also look into  https://github.com/neurodebian/afni/blob/HEAD/debian/rules#L55  about our build flags for cmake

also note that current state of cmake build infrastructure is for AFNI as of  0.20141224~dfsg.1-1~nd80+1 or may be 20150205 and would need some work to update for current state of affairs in AFNI... I will look into updating them in some upcoming days

**Comment by TheChymera** [comment]
@yarikoptic apparently I was not applying all the patches. I'll have to try again and see how this works out.

Regarding the package versions, I am downloading the sources I plan to patch from here https://github.com/neurodebian/afni , *not* from here https://github.com/afniHQ/AFNI .

So if the neurodebian sources at the head of the master branch work with the neurodebian patches, I should be just fine. Do you have any versioning on the repo? I see that the commits have version names, but predictably not all files are updated at once. 

If I just pull from the head of your master, what would be the appropriate name for the version? It's not really 9999/live, and barring that I would have to settle for a version number.  Once I make that, how can I make sure it will always provide the same files and not change with the head of your master branch?

**Comment by yarikoptic** [comment]
versions:  we have tags in our git, which are date based (since there is no reasonable versioning done upstream). e.g.
```
$> git tag
0.20131204_dfsg.1
0.20140612_dfsg.1
0.20140904_dfsg.1
0.20140908_dfsg.1
..
debian/0.20141224_dfsg.1-1
```
for starters -- try to build using the state of the last debian release:  debian/0.20141224_dfsg.1-1  .  That one must build and somewhat work ;)

but also you would need afni-data package  packaging for which is at http://git.debian.org/?p=pkg-exppsy/afni-data.git
but what you really need is the tarball with the data (atlases etc) which obviously don't change much between afni "releases".  You can fetch it here:  http://neuro.debian.net/debian/pool/main/a/afni-data/

**Comment by TheChymera** [comment]
@yarikoptic what's a good place to install the afni data?

**Comment by TheChymera** [comment]
@yarikoptic I'm making progress with the build, but apparently after I apply all the patche and start cmake, it fails because it can't find the gifti sources dir (do I have to get them from somewhere else?)

You can check out my [build log](https://bpaste.net/show/a8587dc6e16e) and the [CMake log](https://bpaste.net/show/ec56f673486b) for more details.

**Comment by yarikoptic** [comment]
On Mon, 06 Jul 2015, Horea Christian wrote:

>    @yarikoptic what's a good place to install the afni data?

we install atlases  under /usr/share/afni/atlases, pics under
/usr/share/afni/pics/  etc

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
On Wed, 08 Jul 2015, Horea Christian wrote:

>    @yarikoptic I'm making progress with the build, but apparently after I
>    apply all the patche and start cmake, it fails because it can't find the
>    gifti sources dir (do I have to get them from somewhere else?)

we packaged that library separately. It originates from
http://www.nitrc.org/projects/gifti

**Comment by TheChymera** [comment]
@yarikoptic so how does neurodebian deal with this? how do you tell cmake to not look for it?

**Comment by TheChymera** [comment]
@yarikoptic I copied the cmake variables used in the [debian rules file](http://anonscm.debian.org/cgit/pkg-exppsy/afni.git/tree/debian/rules).

Now I get [this error message](https://bpaste.net/show/fc09c2cca64a). Apparently the crux of it is NIFTI_INCLUDE_DIR being not set. How should I set it? what should I set it to?

**Comment by yarikoptic** [comment]
On Thu, 09 Jul 2015, Horea Christian wrote:

>    @yarikoptic I copied the cmake variables used in the debian rules file.

>    Now I get this error message. Apparently the crux of it is
>    NIFTI_INCLUDE_DIR being not set. How should I set it? what should I set it
>    to?

are you building own copy of gifti... and nifti (so it doesn't get set)
-- fixup cmake then to 

SET(NIFTI_INCLUDE_DIR  ${CMAKE_SOURCE_DIR}/nifti/niftilib)

or smth like that if you build it locally (now it just runs
FIND_PATH(NIFTI_INCLUDE_DIR... only if using system-wide installed one

don't forget to submit us a patch ;-)

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by TheChymera** [comment]
>SET(NIFTI_INCLUDE_DIR  ${CMAKE_SOURCE_DIR}/nifti/niftilib)
or smth like that if you build it locally (now it just runs
FIND_PATH(NIFTI_INCLUDE_DIR... only if using system-wide installed one

so, what should I do about that error if I am installing system-wide?

> don't forget to submit us a patch ;-)

For what?

**Comment by TheChymera** [comment]
@yarikoptic I'm sorry, but I don't think I understand much from your last reply. I am not building my own copy of gifti (using `-DAFNI_BUILD_LOCAL_GIFTI:BOOL=OFF`) as for nifti, I am unsure whether I am building my own copy - but judging by the fact that CMake fails due to `NIFTI_INCLUDE_DIR` I guess I am?

Do you recommend I build nifti myself or not? What does neurodebian do?

**Comment by TheChymera** [comment]
@yarikoptic I tried to set `-DAFNI_BUILD_LOCAL_NIFTI:BOOL=OFF`, but CMake still fails because `NIFTI_INCLUDE_DIR` is unset.

**Comment by yarikoptic** [comment]
What is your full set of options for cmake? So I could see how it is different from ours

**Comment by TheChymera** [comment]
@yarikoptic how can I get the full set of cmake options? Running `./configure --help` in the source directory?

**Comment by TheChymera** [comment]
@yarikoptic bump?

**Comment by yarikoptic** [comment]
Sorry... I was asking which options did you use? Can't check now man cmake to give answer to your question (phone only mode of life ATM), but nearly all options we introduced used in our debian/rules - did you look at those?

**Comment by TheChymera** [comment]
@yarikoptic  hey! Thank you for getting back on this.

As I said before,  the full list of CMAKE options I pass is the one [here](https://github.com/TheChymera/neurogentoo/blob/80465999149a4103f0a5c9127bd23925a3c8b43c/sci-biology/afni/afni-0_pre20141224.ebuild#L52-L72). I copied them almost verbatim from [the equivalent lines](http://anonscm.debian.org/cgit/pkg-exppsy/afni.git/tree/debian/rules#n55) in the NeuroDebian rules file. 

Should I also include the lines from under [override_dh_auto_cinfigure](http://anonscm.debian.org/cgit/pkg-exppsy/afni.git/tree/debian/rules#n82)?

**Comment by TheChymera** [comment]
@yarikoptic bump?

**Comment by yarikoptic** [comment]
well -- the short answer is "yes".  That variable "DEB_CMAKE_EXTRA_FLAGS" just a variable which defines variables to be passed to the cmake invocation (via dh_auto_configure).  Just that in configure we do two builds -- with dynamic linking and static.

**Comment by TheChymera** [comment]
@yarikoptic  I added those two flags, but now I get the complaint that the configuration is incomplete. [Here](https://bpaste.net/show/bde56c6caa32) is the CMake output log.

Is pre-20141224 (commit debian/0.20141224_dfsg.1-1 ) still the recommended  version for getting CMake-AFNI to compile?

**Comment by yarikoptic** [comment]
it is the 0.20141212~dfsg.1-1 (thus that tag) which last built fine for us on neurodebian so should be a good starting point

where is the complaint specifically? it seems to report succeed for the last checks

if you give me a quick howto get into such env (e.g. Dockerfile which would preinstall all build depends) I could try also to build there

**Comment by TheChymera** [comment]
do you mean `0.20141212~dfsg.1` or `debian/0.20141212~dfsg.1-1` ? there is no `0.20141212~dfsg.1-1`

**Comment by yarikoptic** [comment]
By "0.20141212~dfsg.1-1" I meant our debian release whic was tagged as ... actually I meant 0.20141224~dfsg.1-1.... as "debian/0.20141224_dfsg.1-1" (git doesn't tollerate ~ in the tag, so git-buildpackage converts them to _)

**Comment by TheChymera** [comment]
@yarikoptic 
 I added this to my CMak options set:

`-DNIFTI_INCLUDE_DIR:STRING="/lib/afni/nifti/niftilib"` but now it fails to uild with

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
R_INCLUDE_DIRS
```


what should I set that to?

**Comment by TheChymera** [comment]
Ok, now I also added `-DR_INCLUDE_DIRS:STRING="/lib/afni/R"` (completely invented path).

and now it is asking me for `R_LIB` - how come in your build you do not have to specify thee variables? what should I ideally st them to?

**Comment by TheChymera** [comment]
Now that I gave it some dummy path for that as well, it asks for `VOLPACK_LIBRARY`. What are the proper paths for all these variables?

**Comment by yarikoptic** [comment]
On Mon, 16 Nov 2015, Horea Christian wrote:

> Now that I gave it some dummy path for that as well, it asks for
> VOLPACK_LIBRARY. What are the proper paths for all these variables?

it (cmake) should find it if you have it installed.  Do you have it
installed?

this is where on debian

$> dpkg -L libvolpack1-dev | grep -v -e man/ -e share
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libvolpack.a
/usr/include
/usr/include/volpack.h
/usr/lib/x86_64-linux-gnu/libvolpack.so

**Comment by TheChymera** [comment]
@yarikoptic I see, is this the package that is meant by `libvolpack`? http://sourceforge.net/projects/amide/files/volpack/

Do you have a list with all other external libraries AFNI would depend on? Right now I have 

*dev-libs/expat
*media-libs/netpbm
*media-libs/qhull
*media-video/mpeg-tools
*sci-libs/gsl
*sys-devel/llvm
*virtual/jpeg:0
*x11-libs/libGLw
*x11-libs/libXft
*x11-libs/libXi
*x11-libs/libXpm
*x11-libs/motif[-static-libs]

But it seems I was also missing:

* dev-lang/R
* media-libs/volpack

Is there anything else I am missing? What about `nifti` as you called it? is it a package? Where can I get it from?

**Comment by yarikoptic** [comment]
Check debian/control. You can find information about packages including pointers to upstream at http://packages.Debian.oRg

**Comment by nno** [comment]
@TheChymera is this still an issue?

Since the official AFNI is now hosted at https://github.com/afni/afni, we would like to close down afniHQ entirely. If this is still an issue, can you please re-open at https://github.com/afni/afni?
