### ISSUE TITLE
/src/testGL not building

### ISSUE THREAD

**Issue by TheChymera** [afniHQ/AFNI#5]
Hi guys, I am building AFNI using the `linux_fedora_19_64` Makefile. At the end I am expecting `/src/testGL` to get built, as per the contents of `/src/prog_list.txt`.

Sadly it is not there. Is the file outdated?

I notice `testGL` is mentioned in `/src/Makefile.INCLUDE` - which says:

> Include for MCW AFNI make

I was unable to find out via google what MCW AFNI is - do I realy want to make MCW AFNI?

**Comment by TheChymera** [comment]
This was confusing. Apparently Makefile.INCLUDE actually gets included in the other Makefiles - I did not have to append it manually

**Comment by afni-rwcox** [comment]
"MCW AFNI" is what I called it when I was at MCW = Medical College of Wisconsin.  When I moved to the NIH in 2001, the "MCW" kind of evaporated away.  But not everywhere -- I did not go on a holy quest to eliminate all "MCW"s from the files.  In particular, there are a lot of C functions named "MCW_something()".
